language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text --strict

after_script:
  - php vendor/bin/coveralls -v
